### ISSUE TITLE
app.import is not yet implemented for GlimmerApp

### ISSUE THREAD

**Issue by bstro** [glimmerjs/glimmer-application-pipeline#107] opened 2017-06-02 20:29 UTC
In a fresh project generated from the glimmer blueprint, after installing an addon (in this case, an internal addon as well as ember-redux), upon attemping `ember s`, I receive the following error: 

`app.import is not yet implemented for GlimmerApp`

ember-cli: 2.14.0-beta.2
node: 6.10.3
os: darwin x64

full trace:

```app.import is not yet implemented for GlimmerApp
Error: app.import is not yet implemented for GlimmerApp
    at GlimmerApp.import (/Users/bstro/dev/glimmer-spike/node_modules/@glimmer/application-pipeline/dist/lib/broccoli/glimmer-app.js:131:15)
    at Class.included (/Users/bstro/dev/glimmer-spike/node_modules/ember-maybe-import-regenerator/index.js:29:21)
    at Class.superWrapper [as included] (/Users/bstro/dev/glimmer-spike/node_modules/core-object/lib/assign-properties.js:34:20)
    at addons.map.addon (/Users/bstro/dev/glimmer-spike/node_modules/ember-cli/lib/models/addon.js:383:34)
    at Array.map (native)
    at Class.eachAddonInvoke (/Users/bstro/dev/glimmer-spike/node_modules/ember-cli/lib/models/addon.js:381:24)
    at Class.included (/Users/bstro/dev/glimmer-spike/node_modules/ember-cli/lib/models/addon.js:652:10)
    at Class.superWrapper [as included] (/Users/bstro/dev/glimmer-spike/node_modules/core-object/lib/assign-properties.js:34:20)
    at addons.map.addon (/Users/bstro/dev/glimmer-spike/node_modules/ember-cli/lib/models/addon.js:383:34)
    at Array.map (native)

**Comment by bstro** [comment] 2017-06-02 20:37
In the case of ember-redux, I filed a ticket. Is there something I need to do in order to make our private addons compatible with glimmerjs?

**Comment by locks** [comment] 2017-06-04 23:35
Duplicate of https://github.com/glimmerjs/glimmer-application-pipeline/issues/41.

**Closed by locks** 2017-06-04 23:35 UTC
